import type { DanmakuItem, PositionedDanmaku, AssOptions } from '../../types';
import { layoutDanmaku } from './layout';

export const ASS_DEFAULTS = {
  width: 1920,
  height: 1080,
  fontSize: 48,
  fontName: '黑体',
  duration: 12,
  opacity: 0.8,
} as const;

/** 秒 → ASS 时间戳 H:MM:SS.cc（厘秒） */
export function formatAssTime(seconds: number): string {
  const total = Math.max(0, seconds);
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = Math.floor(total % 60);
  const cs = Math.round((total - Math.floor(total)) * 100);
  const pad = (n: number) => String(n).padStart(2, '0');
  // 四舍五入到厘秒可能进位到 100
  if (cs === 100) return formatAssTime(Math.floor(total) + 1);
  return `${h}:${pad(m)}:${pad(s)}.${pad(cs)}`;
}

/** ASS 文本转义：\ { } 为标记字符，换行统一成软换行 \n */
export function escapeAssText(text: string): string {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}')
    .replace(/\r?\n/g, '\\n');
}

/** 不透明度 0~1 → ASS &HAA& alpha（00=不透明 FF=全透明） */
function assAlpha(opacity: number): string {
  const clamped = Math.min(1, Math.max(0, opacity));
  const alpha = Math.round((1 - clamped) * 255);
  return alpha.toString(16).padStart(2, '0').toUpperCase();
}

/** 弹幕条目 → 完整 ASS 文档（排版 + 渲染） */
export function renderAss(items: DanmakuItem[], options: AssOptions = {}): string {
  const opts = { ...ASS_DEFAULTS, ...options };
  const positioned = layoutDanmaku(items, {
    width: opts.width,
    height: opts.height,
    fontSize: opts.fontSize,
    duration: opts.duration,
  });

  const alpha = assAlpha(opts.opacity);
  const header = [
    '[Script Info]',
    '; Generated by douyudm',
    'ScriptType: v4.00+',
    'Collisions: Normal',
    `PlayResX: ${opts.width}`,
    `PlayResY: ${opts.height}`,
    '',
    '[V4+ Styles]',
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
    `Style: Danmaku,${opts.fontName},${opts.fontSize},&H${alpha}FFFFFF,&H${alpha}FFFFFF,&H${alpha}000000,&H${alpha}000000,0,0,0,0,100,100,0,0,1,2,0,7,0,0,0,1`,
    '',
    '[Events]',
    'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text',
  ];

  const events = positioned.map(dialogueLine);
  return header.concat(events).join('\n') + '\n';
}

function dialogueLine(d: PositionedDanmaku): string {
  const move = `{\\move(${d.x1},${d.y},${d.x2},${d.y})}`;
  return `Dialogue: 0,${formatAssTime(d.start)},${formatAssTime(d.end)},Danmaku,,0,0,0,,${move}${escapeAssText(d.text)}`;
}
